dist: trusty
sudo: required
language: node_js
node_js:
  - "lts/*"
  - "10"
  - "9"
  - "8"
cache: npm
skip_cleanup: true

os:
  - linux

jobs:
  include:
    - stage: coveralls
      node_js: lts/*
      script: npm run coveralls
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      script: npm run doc
      skip_cleanup: true
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
      if: branch = master AND type != pull_request