dist: trusty
sudo: required
language: node_js
node_js:
  - "lts/*"
  - "10"
  - "9"
  - "8"
cache: npm
script: 'true'
os:
  - linux

jobs:
  include:
    - stage: test
      script: npm run test
      after_success: npm run coveralls
    - stage: release
      node_js: lts/*
      script: npm run doc
      skip_cleanup: true
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
      if: branch = master AND type != pull_request